name: Build and deploy to production on main push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 20 and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build project
        run: npm ci && npm run build

      - name: Install openconnect
        run: sudo apt-get update && sudo apt-get install -y openconnect

      - name: Connect to Cisco AnyConnect VPN
        run: |
          echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect \
            --user=${{ secrets.VPN_USERNAME }} \
            --passwd-on-stdin \
            ${{ secrets.VPN_SERVER }} \
            --background
          sleep 10

      - name: Verify VPN connection
        run: curl ifconfig.me

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          compress: false
          localDir: dist/
          remoteDir: www/
